export default Object.freeze({
  BUBBLE_SCATTER: 'BUBBLE_SCATTER',
  BAR_HORIZONTAL: 'BAR_HORIZONTAL',
  BAR_VERTICAL: 'BAR_VERTICAL',
  LINE: 'LINE',
  MAP: 'MAP',
  BUBBLE_CARTOGRAM: 'BUBBLE_CARTOGRAM',
  BUBBLE_PACKED_CARTOGRAM: 'BUBBLE_PACKED_CARTOGRAM',
  HEXAGONAL_CARTOGRAM: 'HEXAGONAL_CARTOGRAM',
  NONE: 'NONE',
});
