export default Object.freeze({
  AXES: 'axes',
  BAR_HORIZONTAL: 'morphable-rect',
  BAR_VERTICAL: 'morphable-rect',
  BUBBLE: 'morphable-bubble',
  BUBBLE_LEGEND: 'bubble-legend',
  CARTOGRAM: 'morphable-rect',
  CHART_SPACE: 'chart-space',
  COLOR_LEGEND: 'color-legend',
  LINE: 'morphable-line',
  LEGEND_GROUP: 'legend-group',
  MAP: 'morphable-geo-path',
  MORPHABLES: 'morphablesGroup',
  NONE: 'NONE',
  X_AXIS: 'x-axis',
  Y_AXIS_LABEL: 'y-axis-label',
  X_AXIS_LABEL: 'x-axis-label',
  Y_AXIS: 'y-axis',
});
