export default Object.freeze({
  TRANSITION_DURATION: 1000,
  TRANSITION_DELAY: 25,
  ANIMATE_IN_SEQUENCE: 'ANIMATE_IN_SEQUENCE',
  ANIMATE_ALL: 'ANIMATE_ALL',
  MAX_NUMBER_OF_PIECES_IN_PATH: 15,
  FLUBBER_INTERPOLATE_OPTIONS: { maxSegmentLength: 3, single: true },
  DEFAULT_MISSING_COLOR: 'none',
});
